const productData = [
    {
      id: 1,
      image: require("./assets/Images/product1.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Classic",
      price: "$675.00",
      rating: 3,
      isDiscount: false,
      precentage: "31%",
    },
    {
      id: 2,
      image: require("./assets/Images/product2.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Sales",
      discountprice: "$103.00",
      price: "$675.00",
      rating: 3,
      isDiscount: true,
      precentage: "31%",
    },
    {
      id: 3,
      image: require("./assets/Images/product7.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Classic",
      price: "$675.00",
      rating: 4,
      isDiscount: false,
      precentage: "31%",
    },
    {
      id: 4,
      image: require("./assets/Images/product4.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Classic",
      discountprice: "$103.00",
      price: "$675.00",
      rating: 4,
      isDiscount: true,
      precentage: "31%",
    },
    {
      id: 5,
      image: require("./assets/Images/product8.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Classic",
      price: "$675.00",
      rating: 4,
      isDiscount: false,
      precentage: "31%",
    },
    {
      id: 6,
      image: require("./assets/Images/product6.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Classic",
      price: "$675.00",
      rating: 4,
      isDiscount: false,
      precentage: "31%",
    },
    {
      id: 7,
      image: require("./assets/Images/product7.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Sales",
      price: "$675.00",
      rating: 4,
      isDiscount: false,
      precentage: "31%",
    },
    {
      id: 8,
      image: require("./assets/Images/product8.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Classic",
      price: "$675.00",
      rating: 4,
      isDiscount: false,
      precentage: "31%",
    },
    {
      id: 9,
      image: require("./assets/Images/product3.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Sales",
      price: "$675.00",
      rating: 4,
      isDiscount: false,
      precentage: "31%",
    },
    {
      id: 10,
      image: require("./assets/Images/product5.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Modern",
      price: "$675.00",
      rating: 4,
      isDiscount: false,
      precentage: "31%",
    },
  
    {
      id: 11,
      image: require("./assets/Images/product1.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Classic",
      price: "$675.00",
      rating: 4,
    },
    {
      id: 12,
      image: require("./assets/Images/product2.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Classic",
      price: "$675.00",
      rating: 4,
    },
    {
      id: 13,
      image: require("./assets/Images/product1.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Modern",
      price: "$675.00",
      rating: 4,
    },
  
    {
      id: 14,
      image: require("./assets/Images/product1.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Classic",
      price: "$675.00",
      rating: 4,
    },
    {
      id: 15,
      image: require("./assets/Images/product1.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Classic",
      price: "$675.00",
      rating: 4,
    },
    {
      id: 16,
      image: require("./assets/Images/product1.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Modern",
      price: "$675.00",
      rating: 4,
    },
  
    {
      id: 17,
      image: require("./assets/Images/product1.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Classic",
      price: "$675.00",
      rating: 4,
      isDiscount: true,
      precentage: "31%",
    },
    {
      id: 18,
      image: require("./assets/Images/product1.png"),
      type: "Bag Type",
      title: "Bag And Accessory Bout..",
      category: "Modern",
      price: "$675.00",
      rating: 4,
      isDiscount: true,
      precentage: "31%",
    },
  ];
  
  export default productData;
  